import Head from 'next/head'
import Image from 'next/image'
import React from "react";
import styles from './about.module.scss'

export default function Index() {
  return (
    <div >
      <Head>
        <title>李昊的Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles['banner']}>

      </div>


    </div>
  )
}
